//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cari()
        {
            this.CariConfirmations = new HashSet<CariConfirmation>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> TL { get; set; }
        public Nullable<decimal> Euro { get; set; }
        public Nullable<decimal> Dollar { get; set; }
        public int FirmaId { get; set; }
        public string Uniqueidentifier { get; set; }
        public string WhoInserted { get; set; }
        public string WhoUpdated { get; set; }
        public string WhoDeleted { get; set; }
        public Nullable<System.DateTime> WhenInserted { get; set; }
        public Nullable<System.DateTime> WhenUpdated { get; set; }
        public Nullable<System.DateTime> WhenDeleted { get; set; }
        public string VoucherNo { get; set; }
        public string Pax { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> TurId { get; set; }
        public Nullable<int> OtelId { get; set; }
        public Nullable<int> SatisSorumlusu_Id { get; set; }
        public bool Confirmed { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Otel Otel { get; set; }
        public virtual SatisSorumlusu SatisSorumlusu { get; set; }
        public virtual Tur Tur { get; set; }
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CariConfirmation> CariConfirmations { get; set; }
    }
}
