//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelInnEntities : DbContext
    {
        public TravelInnEntities()
            : base("name=TravelInnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firma> Firmas { get; set; }
        public virtual DbSet<FirmaTemsilcisi> FirmaTemsilcisis { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Odeme> Odemes { get; set; }
        public virtual DbSet<OdemeLog> OdemeLogs { get; set; }
        public virtual DbSet<Uyruk> Uyruks { get; set; }
        public virtual DbSet<CariLog> CariLogs { get; set; }
        public virtual DbSet<View_CariOdemeExcel> View_CariOdemeExcel { get; set; }
        public virtual DbSet<View_FirmaBakiye> View_FirmaBakiye { get; set; }
        public virtual DbSet<Banka> Bankas { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Otel> Otels { get; set; }
        public virtual DbSet<SatisSorumlusu> SatisSorumlusus { get; set; }
        public virtual DbSet<Tur> Turs { get; set; }
        public virtual DbSet<View_YaklasanKayitlar> View_YaklasanKayitlar { get; set; }
        public virtual DbSet<View_UyrukCariAdedi> View_UyrukCariAdedi { get; set; }
        public virtual DbSet<View_CariSearch> View_CariSearch { get; set; }
        public virtual DbSet<Cari> Caris { get; set; }
        public virtual DbSet<CariConfirmation> CariConfirmations { get; set; }
    }
}
