//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> TL { get; set; }
        public Nullable<decimal> Euro { get; set; }
        public Nullable<decimal> Dollar { get; set; }
        public string FirmaIsmi { get; set; }
        public string Uniqueidentifier { get; set; }
        public string Who { get; set; }
        public Nullable<System.DateTime> When { get; set; }
        public string Action { get; set; }
        public string Banka { get; set; }
    }
}
