//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeme
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> TL { get; set; }
        public Nullable<decimal> Euro { get; set; }
        public Nullable<decimal> Dollar { get; set; }
        public int FirmaId { get; set; }
        public string Uniqueidentifier { get; set; }
        public string WhoInserted { get; set; }
        public string WhoUpdated { get; set; }
        public string WhoDeleted { get; set; }
        public Nullable<System.DateTime> WhenInserted { get; set; }
        public Nullable<System.DateTime> WhenUpdated { get; set; }
        public Nullable<System.DateTime> WhenDeleted { get; set; }
        public Nullable<int> Banka_Id { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual Banka Banka { get; set; }
    }
}
