//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisSorumlusu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SatisSorumlusu()
        {
            this.Caris = new HashSet<Cari>();
        }
    
        public int Id { get; set; }
        public string Ismi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string Uniqueidentifier { get; set; }
        public string WhoInserted { get; set; }
        public string WhoUpdated { get; set; }
        public string WhoDeleted { get; set; }
        public Nullable<System.DateTime> WhenInserted { get; set; }
        public Nullable<System.DateTime> WhenUpdated { get; set; }
        public Nullable<System.DateTime> WhenDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cari> Caris { get; set; }
    }
}
