//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UyrukCariAdedi
    {
        public int Id { get; set; }
        public string Uyrugu { get; set; }
        public string Uniqueidentifier { get; set; }
        public int CariAdedi { get; set; }
    }
}
