//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CariOdemeExcel
    {
        public int Id { get; set; }
        public int FirmaId { get; set; }
        public string Firma { get; set; }
        public Nullable<System.DateTime> CTarih { get; set; }
        public string CAciklama { get; set; }
        public Nullable<decimal> CTL { get; set; }
        public Nullable<decimal> CEuro { get; set; }
        public Nullable<decimal> CDollar { get; set; }
        public string CMusteri_AdiSoyadi { get; set; }
        public string CTur_Adi { get; set; }
        public string COtel_Adi { get; set; }
        public string SatisSorumlusu { get; set; }
        public Nullable<System.DateTime> OTarih { get; set; }
        public string OAciklama { get; set; }
        public Nullable<decimal> OTL { get; set; }
        public Nullable<decimal> OEuro { get; set; }
        public Nullable<decimal> ODollar { get; set; }
        public string Banka_Adi { get; set; }
    }
}
