//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_YaklasanKayitlar
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string FirmaIsmi { get; set; }
        public string Aciklama { get; set; }
        public string Sorumlu { get; set; }
        public Nullable<decimal> TL { get; set; }
        public Nullable<decimal> Euro { get; set; }
        public Nullable<decimal> Dollar { get; set; }
        public string VN { get; set; }
        public string Pax { get; set; }
        public string Musteri { get; set; }
        public string Uyrugu { get; set; }
        public string Tur { get; set; }
        public string Otel { get; set; }
        public bool Confirmed { get; set; }
    }
}
