//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelInn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FirmaBakiye
    {
        public int FirmaId { get; set; }
        public string Firma { get; set; }
        public decimal Cari_TL { get; set; }
        public decimal Cari_Euro { get; set; }
        public decimal Cari_Dollar { get; set; }
        public decimal Odeme_TL { get; set; }
        public decimal Odeme_Euro { get; set; }
        public decimal Odeme_Dollar { get; set; }
        public Nullable<decimal> Bakiye_TL { get; set; }
        public Nullable<decimal> Bakiye_Euro { get; set; }
        public Nullable<decimal> Bakiye_Dollar { get; set; }
    }
}
